#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : castellan
Version  : 0.4.0
Release  : 18
URL      : https://pypi.python.org/packages/source/c/castellan/castellan-0.4.0.tar.gz
Source0  : https://pypi.python.org/packages/source/c/castellan/castellan-0.4.0.tar.gz
Summary  : Generic Key Manager interface for OpenStack
Group    : Development/Tools
License  : Apache-2.0
Requires: castellan-python
Requires: Babel
Requires: cryptography
Requires: oslo.config
Requires: oslo.context
Requires: oslo.log
Requires: oslo.policy
Requires: oslo.serialization
Requires: oslo.utils
Requires: pbr
BuildRequires : configparser-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
=========
Castellan
=========
Generic Key Manager interface for OpenStack.
* License: Apache License, Version 2.0
* Documentation: http://docs.openstack.org/developer/castellan
* Source: http://git.openstack.org/cgit/openstack/castellan
* Bugs: http://bugs.launchpad.net/castellan

%package python
Summary: python components for the castellan package.
Group: Default

%description python
python components for the castellan package.


%prep
%setup -q -n castellan-0.4.0

%build
export LANG=C
export SOURCE_DATE_EPOCH=1489280714
python2 setup.py build -b py2
python3 setup.py build -b py3

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
py.test-2.7 --verbose py2 || :
%install
export SOURCE_DATE_EPOCH=1489280714
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
