#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : castellan
Version  : 1.3.1
Release  : 35
URL      : https://files.pythonhosted.org/packages/a7/0d/7a336fdeb4b5c251383443caa80ea30062847fb20a63af22c008f382d23b/castellan-1.3.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/a7/0d/7a336fdeb4b5c251383443caa80ea30062847fb20a63af22c008f382d23b/castellan-1.3.1.tar.gz
Summary  : Generic Key Manager interface for OpenStack
Group    : Development/Tools
License  : Apache-2.0
Requires: castellan-license = %{version}-%{release}
Requires: castellan-python = %{version}-%{release}
Requires: castellan-python3 = %{version}-%{release}
Requires: Babel
Requires: cryptography
Requires: keystoneauth1
Requires: oslo.config
Requires: oslo.context
Requires: oslo.i18n
Requires: oslo.log
Requires: oslo.utils
Requires: pbr
Requires: python-barbicanclient
Requires: requests
Requires: stevedore
BuildRequires : Babel
BuildRequires : buildreq-distutils3
BuildRequires : cryptography
BuildRequires : keystoneauth1
BuildRequires : oslo.config
BuildRequires : oslo.context
BuildRequires : oslo.i18n
BuildRequires : oslo.log
BuildRequires : oslo.utils
BuildRequires : pbr
BuildRequires : python-barbicanclient
BuildRequires : requests
BuildRequires : stevedore

%description
=========
Castellan
=========
Generic Key Manager interface for OpenStack.
* License: Apache License, Version 2.0
* Documentation: https://docs.openstack.org/castellan/latest
* Source: https://opendev.org/openstack/castellan
* Bugs: https://bugs.launchpad.net/castellan
* Release notes: https://docs.openstack.org/releasenotes/castellan

%package license
Summary: license components for the castellan package.
Group: Default

%description license
license components for the castellan package.


%package python
Summary: python components for the castellan package.
Group: Default
Requires: castellan-python3 = %{version}-%{release}

%description python
python components for the castellan package.


%package python3
Summary: python3 components for the castellan package.
Group: Default
Requires: python3-core

%description python3
python3 components for the castellan package.


%prep
%setup -q -n castellan-1.3.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1567638540
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
py.test-2.7 --verbose py2 || :
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/castellan
cp LICENSE %{buildroot}/usr/share/package-licenses/castellan/LICENSE
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/castellan/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
